# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_dispatch:
  push:
    branches: 
      - '!main'
#      - '*'         # matches every branch that doesn't contain a '/'
#      - '*/*'       # matches every branch containing a single '/'
#      - '**'        # matches every branch
#      - '!main'     # excludes main  
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
#        cache: 'sbt'
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
#    - name: Run tests & Coverage Report
#      run: sbt coverage test coverageReport
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v3
#      with:
#        files: common/target/scala-2.12/coverage-report/cobertura.xml,core/target/scala-2.12/coverage-report/cobertura.xml,teskit/target/scala-2.12/coverage-report/cobertura.xml
#        flags: unittests
#        fail_ci_if_error: true
#        verbose: true
    - name: Run tests
      run: STRIPE_CLIENT_ID=${{secrets.STRIPE_CLIENT_ID}} STRIPE_API_KEY=${{secrets.STRIPE_API_KEY}} sbt clean test
      env:
        STRIPE_CLIENT_ID: ${{secrets.STRIPE_CLIENT_ID}}
        STRIPE_API_KEY: ${{secrets.STRIPE_API_KEY}}
    # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    # - name: Upload dependency graph
    #   uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
#          cache: 'sbt'
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck